### ISSUE TITLE
选词数字与文字不对齐？

### ISSUE THREAD

**Issue by baucd** [winjeg/fcitx-skins#1]
请问怎么设置使得选词数字与文字对齐？谢谢！

**Comment by winjeg** [comment]
有图么？ 我不知道怎么就不对齐了， 然后另外fcitx-config-tool 可以调整字体的大小之类的你可以试试调整之后是不是可以。

**Comment by baucd** [comment]
![image](https://user-images.githubusercontent.com/14149144/51234334-71251800-19a7-11e9-81df-0d1fa4e8afcc.png)
<img width="613" alt="screen shot 2019-01-16 at 15 59 46" src="https://user-images.githubusercontent.com/14149144/51234595-21931c00-19a8-11e9-8131-5b2e97b276a3.png">
就像上图一样，前面的数字序号与后面的文字感觉没有对齐，请问能做到下图那样的效果吗？

**Comment by winjeg** [comment]
貌似调整不了。 其实这个你可以看到英文的这个是对齐的，理论上讲是整体对齐的。而且我研究了以下， 并没有发现可以调整后选项， 候选项/序号与拼音串的相对位置关系貌似是定死的， 调整不动。
阁下一看就是五笔打字员，哈哈。 issue我关了， 差这一点点也不影响。。。。
![screenshot from 2019-01-19 13-30-29](https://user-images.githubusercontent.com/7270177/51422724-6f00ca80-1bee-11e9-8a00-db98194466e3.png)
